version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: mysqldb
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./data:/docker-entrypoint-initdb.d
      - ./seeding:/var/db
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
